---
- hosts: HDPC.cjlss.co.uk
  become: yes
  vars:
    var1: 80
  tasks:
  - name: Package Update
    shell: apt-get update >/tmp/update.lst

  - fetch: src=/tmp/update.lst dest=/tmp/prefix-{{ inventory_hostname }} flat=yes



